-- Create a view combining data from multiple years
CREATE VIEW hotels AS
SELECT * FROM year2018
UNION ALL
SELECT * FROM year2019
UNION ALL
SELECT * FROM year2020;
-- This view combines data from the years 2018, 2019, and 2020 into a single dataset.

----------------------------------------------------------------------------------

-- retrieves the top 10 countries with the highest revenue.
WITH RevenueByCountry AS (
SELECT 
    hotel, 
    country, 
    arrival_date_year, 
	ROUND(SUM((stays_in_week_nights + stays_in_weekend_nights) * adr), 0) AS revenue
FROM 
    hotels
GROUP BY 
    hotel, country, arrival_date_year 
)
SELECT  TOP 10
    country, 
    SUM(revenue) AS total_revenue
FROM 
    RevenueByCountry
GROUP BY 
    country 
ORDER BY 
    total_revenue DESC;
-- This query calculates the total revenue generated by hotels in different countries
/*
PRT (Portugal) has the highest total revenue of 17,598,253.
GBR (United Kingdom) follows with 5,440,740.
Other countries with significant total revenue include FRA (France), ESP (Spain), DEU (Germany), IRL (Ireland), and ITA (Italy).
BRA (Brazil) and NLD (Netherlands) are also present in the top 10 list with 875,930 and 811,445 in total revenue, respectively.